class PollingModel {
  final String name;

  PollingModel({
    required this.name,
  });
}

final List<PollingModel> pollingData = [
  PollingModel(name: 'LAFIYAWO, KOFAR JAURO'),
  PollingModel(name: 'MARORI / WUI-WUI, KOFAR JAURO'),
  PollingModel(name: 'AKKO, AKKO PRI. SCH.'),
  PollingModel(name: 'S/YAKI/J. HAMMA, AKKO PRI. SCH.'),
  PollingModel(name: 'GAMADADI T/WADA, KOFAR JAURO'),
  PollingModel(name: 'LAWANTI, K. J. LAWANTI'),
  PollingModel(name: 'JALINGO, KOFAR JAURO'),
  PollingModel(name: 'KOMBANI, KOFAR JAURO'),
  PollingModel(name: 'DUNAMARI â€“ BOGGAGEL, LAWANTI PRI. SCH.'),
  PollingModel(name: 'ALINGO / AKKO, K. S. LAWANTI'),
  PollingModel(name: 'DOLLI JILIM â€“ DOLLI KUTURE, DOLLI PRI. SCH.'),
  PollingModel(name: 'DON DORIYA â€“ DOLLI NGALDA, DOLLI PRI. SCH.'),
  PollingModel(name: 'KATAM â€“ GURU â€“ MODOWA, KOFAR JAURO'),
  PollingModel(name: 'WURO DOLE â€“ MUNDA, WURO DOLE PRI. SCH.'),
  PollingModel(name: 'LAWO DODDO â€“ FESHARE, KOFAR JAURO'),
  PollingModel(name: 'BULA KYARI, KOFAR S. BULA'),
  PollingModel(name: 'LAMIDO BANGAJE, BULA PRI. SCH.'),
  PollingModel(name: 'JAN GERAWO â€“ G.J. SHEHU, K. J. SHEHU'),
  PollingModel(name: 'GUDDE SAKI, KOFAR JAURO'),
  PollingModel(name: 'YOLDE JANI / KUYUNTU, JAMJI KOFAR JAURO'),
  PollingModel(name: 'JAMJI, J. JAMJI'),
  PollingModel(name: 'BULA â€“ BULA, KOFAR J.'),
  PollingModel(name: 'TUDU WADA â€“ K/JAURO UBAN-DOMA'),
  PollingModel(name: 'ZONGO MARI, K. S. ZONGO MARI'),
  PollingModel(name: 'DAGARAWO â€“ MARKE, DAGARAWO PRI. SCH.'),
  PollingModel(name: '026 JAURO HAMMA, K.J. JUNGUDO EXISTING PU'),
  PollingModel(name: '027 MALAM BURARI, K.J. BURARI EXISTING PU'),
  PollingModel(name: '028 WURO BOGGA, AKKO MATERNITY EXISTING PU'),
  PollingModel(name: '029 ZONGOMARI, SIDE OF ZONGOMARI PRI. SCH. EXISTING PU'),
  PollingModel(name: '030 ZUKKUTU, K.J. ZUKKUTU EXISTING PU'),
  PollingModel(name: '031 JALINGO, DISPENSARY EXISTING PU'),
  PollingModel(name: '032 LAWANTI II K.J LAWANTI NEW PU'),
  PollingModel(name: '001 YANKARI, KOFAR S. YAKI EXISTING PU'),
  PollingModel(name: '002 DOMDOMTI / YANKARI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '003 YANKARI AREWA /Y. YAMMA, K. J. DAJJI EXISTING PU'),
  PollingModel(name: '004 KOMBANI BABA, K. J. BULA EXISTING PU'),
  PollingModel(name: '005 KOMBANI ISA / NGAJI, K. J. KOMBANI EXISTING PU'),
  PollingModel(
      name: '006 PADAYA ARDO /PADAYA G., KOFAR JAURO PADAYA EXISTING PU'),
  PollingModel(name: '007 TABRA I, KOFAR S. YAKI EXISTING PU'),
  PollingModel(name: '008 TABRA II, KOFAR S. YAKI EXISTING PU'),
  PollingModel(name: '009 TABRA GOBONA, KOFAR S. GOBONA EXISTING PU'),
  PollingModel(name: '010 KALAJANGA, KOFAR J. KALAJANGA EXISTING PU'),
  PollingModel(name: '011 MALAM IZZU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '012 ARDO BOYI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '013 GALDI MARI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '014 WURO BOKKI, KOFAR JAURO I EXISTING PU'),
  PollingModel(name: '015 WURO BOKKI, KOFAR JAURO II EXISTING PU'),
  PollingModel(name: '016 B.C.G.A. / BOGO I, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '017 B.C.G.A. / BOGO II, KOFAR BASHAR EXISTING PU'),
  PollingModel(name: '018 B.C.G.A. / BOGO III, KOFAR BASHAR EXISTING PU'),
  PollingModel(name: '019 B.C.G.A. / BOGO IV, KOFAR BASHAR EXISTING PU'),
  PollingModel(name: '020 B.C.G.A. BOGO V, K. MAI UNG. UMMAR EXISTING PU'),
  PollingModel(name: '021 B.C.G.A. BOGO VI, K. MAI UNG. UMMAR EXISTING PU'),
  PollingModel(name: '022 B.C.G.A. BOGO VII, K. J. GIDIM EXISTING PU'),
  PollingModel(name: '023 B.C.G.A. BOGO VIII, K. ADAMU WAZIRI EXISTING PU'),
  PollingModel(name: '024 JAURO BAKARI, K. J. BAKARI EXISTING PU'),
  PollingModel(name: '025 SHONGO J. BAKARI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '026 SHONGO HAMMA, S. HAMMA PRI SCH. EXISTING PU'),
  PollingModel(name: '027 SHONGO IDIRISA, S. IDIRISA PRI. SCH. EXISTING PU'),
  PollingModel(name: '028 TUMPURE, K. J. TUMPURE EXISTING PU'),
  PollingModel(name: '029 WURO BIRIJI, WURO BIRIJI PRI. SCH. EXISTING PU'),
  PollingModel(name: '030 J. BOSE/JADA, KOFAR JAURO JADA EXISTING PU'),
  PollingModel(name: '031 MAZADU, KOFAR J. MAZADU EXISTING PU'),
  PollingModel(name: '032 WURO JULI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '033 WURO MALUM, KOFAR J. MALUM EXISTING PU'),
  PollingModel(name: '034 M. YAYA / W. SHILE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '035 M. USMAN / HAMMAN DOGO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '036 BOMALA / BAPPA SIRA, KOFAR JAURO BOMALA EXISTING PU'),
  PollingModel(name: '037 HAMMDU KAFI / MASINA, KOFAR J. HAMMA EXISTING PU'),
  PollingModel(name: '038 GARKO / MAJIDADI, GARKO PRI. SCH. EXISTING PU'),
  PollingModel(name: '039 MAJI DADI / DAMBA / HAMMA, K.J. DAMDA EXISTING PU'),
  PollingModel(name: '040 SIS BAKO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '041 HAMMA GOLO, KOFAR JAURO HAMMA EXISTING PU'),
  PollingModel(name: '042 WUDIL /WURO DINDI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '043 MAJI DADI / KUDEMA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '044 GONA MELTARA, GONA PRI. SCH. EXISTING PU'),
  PollingModel(name: '045 KUNDULUM / MADAKI, KOFAR J. GALADIMA EXISTING PU'),
  PollingModel(name: '046 BETO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '047 ZAGAINA, KONDULUM PRI. SCH. EXISTING PU'),
  PollingModel(name: '048 GIRGAM, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '049 KUNDULUM, KUNDULUM PRI. SCH. EXISTING PU'),
  PollingModel(
      name: '050 GARIN SHEHU WURO BIRIJI, KOFAR JAURO SHEHU EXISTING PU'),
  PollingModel(name: '051 BARUNDE, KOFAR MAI ANGUWA BARUNDE EXISTING PU'),
  PollingModel(name: '052 GARKO, DISPENSARY EXISTING PU'),
  PollingModel(name: '053 DAN IYA, KUNDULUM MATERNITY NEW PU'),
  PollingModel(name: '054 ARAWA â€ ̃Bâ€TM PRI. SCHOOL NEW PU'),
  PollingModel(name: '055 TUDUN-WADAN KUNDULUM NEW PU'),
  PollingModel(name: '056 WURO KESA NEW PU'),
  PollingModel(name: '057 KUNDULUM, OPEN SPACE NEW PU'),
  PollingModel(name: '058 BABA DIDI NEW PU'),
  PollingModel(name: '059 GIRGAM II , GIRGAM PRI SCH NEW PU'),
  PollingModel(name: '060 B.C.G.A/ BOGO II MODEL P.H.C.C NEW PU'),
  PollingModel(name: '061 B.C.G.A/BOGO III , BOGO PRI SCHOOL NEW PU'),
  PollingModel(name: '062 B.C.G.A X/ BOGO PRI. SCH NEW PU'),
  PollingModel(name: '063 B.C.G.A XI/ BOGO PRI. SCH NEW PU'),
  PollingModel(name: '064 B.C.G.A XII/ BOGO PRI. SCH NEW PU'),
  PollingModel(name: '065 B.C.G.A XIII/ BOGO PRI. SCH NEW PU'),
  PollingModel(name: '066 SABON GARIN BOGO PRIMARY SCH NEW PU'),
  PollingModel(name: '067 SABON GARIN BOGO MATERNITY NEW PU'),
  PollingModel(name: '068 GARIN SHEHU BOREHOLE NEW PU'),
  PollingModel(name: '069 TABRA GOBONA II, BOREHOLE NEW PU'),
  PollingModel(name: '070 TABRA S. YAKI III, BOREHOLE NEW PU'),
  PollingModel(name: '071 ARDO BOYI II NEW PU'),
  PollingModel(name: '072 GALDI MARI SOLAR BOREHOLE NEW PU'),
  PollingModel(name: '073 BARUNDE GABAR NEW PU'),
  PollingModel(name: '074 BARUNDE SECOND TRANSFORMER NEW PU'),
  PollingModel(name: '075 KOICA PRI. SCH BARUNDE NEW PU'),
  PollingModel(name: '076 BARUNDE YAMMA, SOLAR BOREHOLE NEW PU'),
  PollingModel(name: '077 BARUNDE PRIMARY SCH NEW PU'),
  PollingModel(name: '078 YARIMA QUARTERS, DAN BANGA TRANSFORMER NEW PU'),
  PollingModel(name: '079 BOMALA PRIMARY SCHOOL NEW PU'),
  PollingModel(name: '080 MASINA TRANSFORMER III NEW PU'),
  PollingModel(name: '081 LIMAN BABBA PRIMARY SCH. NEW PU'),
  PollingModel(name: '082 BAGADAZA K. ALI WANZAM BOREHOLE NEW PU'),
  PollingModel(name: '083 RIYADH TRANSFORMER I NEW PU'),
  PollingModel(name: '084 HAMMADU KAFI MATERNITY NEW PU'),
  PollingModel(name: '085 TUDUN WADAN HAMMADU KAFI NEW PU'),
  PollingModel(name: '086 HAMMADU KAFI YAMMA GINDIN BOREHOLE NEW PU'),
  PollingModel(name: '087 WURO SHIâ€TME II NEW PU'),
  PollingModel(name: '088 NAYINAWA RIMARY SCHOOL NEW PU'),
  PollingModel(name: '089 WURO JULI II, PRI SCHOOL NEW PU'),
  PollingModel(name: '090 WURO BIRIJI II, W. BIRIJI PRI SCHOOL NEW PU'),
  PollingModel(name: '091 WURO BIRIJI PRIMARY HEALTH CENTRE NEW PU'),
  PollingModel(name: '092 HAMPATE K. J, OPEN SPACE NEW PU'),
  PollingModel(name: '093 GONA MEL TARA II , GONA PRI SCH NEW PU'),
  PollingModel(name: '094 GONA MEL TARA III , GONA PRI SCH NEW PU'),
  PollingModel(name: '095 YANKARI II, PRIMARY SCHOOL NEW PU'),
  PollingModel(name: '096 ABUBAKAR HABU HASHIDU ESTATE I NEW PU'),
  PollingModel(name: '097 ABUBAKAR HABU HASHIDU ESTATE II NEW PU'),
  PollingModel(name: '098 TUMPURE PRI SCHOOL II NEW PU'),
  PollingModel(name: '099 TUMPURE PRI SCHOOL III NEW PU'),
  PollingModel(name: '100 TUMPURE PRI SCHOOL IV NEW PU'),
  PollingModel(name: '101 TUMPURE PRI SCHOOL V NEW PU'),
  PollingModel(name: '102 TUMPURE PRI SCHOOL VI NEW PU'),
  PollingModel(name: '103 TUMPURE PRI SCHOOL VII NEW PU'),
  PollingModel(name: '104 TUMPURE PRI SCHOOL VIII NEW PU'),
  PollingModel(name: '105 TUMPURE PRI SCHOOL IX NEW PU'),
  PollingModel(name: '106 TUMPURE PRI SCHOOL X NEW PU'),
  PollingModel(name: '107 SHONGO HAMMA II NEW PU'),
  PollingModel(name: '108 WURO BANDU NEW PU'),
  PollingModel(name: '109 INVESTMENT QUATERS NEW PU'),
  PollingModel(name: '110 LABOUR QUARTERS NEW PU'),
  PollingModel(name: '111 SHONGO IDIRISA PRI SCH II NEW PU'),
  PollingModel(name: '112 LAFIYA MANGO NEW PU'),
  PollingModel(name: '001 TUDUN WADA, KALSHINGI PRI. SCH. EXISTING PU'),
  PollingModel(name: '002 PUKUMA, KALSHINGI PRI. SCH. EXISTING PU'),
  PollingModel(name: '003 BATARI, KOFAR SARKI EXISTING PU'),
  PollingModel(name: '004 KULUM / WURO WAKILI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '005 YOLO LIMAN, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '006 WURO SHERIF, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '007 ABBAS / H / BUZU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '008 BATARI / G / TUGGA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '009 WURO WAKILI / BAKU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '010 SHILO WAZIRI, SHILO PRI. SCH. EXISTING PU'),
  PollingModel(name: '011 SHILO MAMUDA, KOFAR JAURO EXISTING PU'),
  PollingModel(
      name: '012 ABBA KALU / ABBA KAYEL, KOFAR J. IBRAHIM EXISTING PU'),
  PollingModel(name: '013 LARO TUMFURE, K. JAURO IBRAHIM EXISTING PU'),
  PollingModel(name: '014 SHILO J. IBRAHIM, KOFAR ABARE EXISTING PU'),
  PollingModel(name: '015 SHILO ABORE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '016 LARIYE J. AUDI, KOFAR JAURO AUDI EXISTING PU'),
  PollingModel(name: '017 FUKURA / BAROROJI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '018 TAUDOMA / ALHAJI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '019 SHILO M. UMARU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '020 BEGUWA / ABBAS, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '021 GUJUBA, GUJUBA PRI. SCH. EXISTING PU'),
  PollingModel(name: '022 NAYINAWA KOROJI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '023 BARRI/GALO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '024 NYABU/PARE, NEAR PARE PRI. SCH. EXISTING PU'),
  PollingModel(name: '025 PARE / KOLOBAYO / BUBA , KOFAR JAURO EXISTING PU'),
  PollingModel(name: '026 W/GOLO KAGANA, TEMPORARY SHADE/G. JABBA EXISTING PU'),
  PollingModel(name: '027 WUDIL/W. DOLE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '028 GABUKKA/JAMTARI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '029 DAGARANKEW, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '030 SARKI SHANU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '031 PANDAYA/MADAKI/P. BOYI, KOFAR JAURO EXISTING PU'),
  PollingModel(
      name: '032 PANDAYA HAJINA/PANDAYA TUKUMA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '033 ZORO/TUKULMAYEL J., KOFAR JAURO EXISTING PU'),
  PollingModel(name: '034 KUMU WAJA, KOFAR JAURO DAUDA EXISTING PU'),
  PollingModel(name: '035 BATARI/ G. TUGGA II, KALSHINGI PRI. SCH NEW PU'),
  PollingModel(name: '036 SHILO WAZIRI , SHILO WAZIRI PRI. SCH NEW PU'),
  PollingModel(name: '001 KASHERE GABAS, K. TAFIDA EXISTING PU'),
  PollingModel(name: '002 KANON KASHERE, PRI. SCH. EXISTING PU'),
  PollingModel(name: '003 KANON KASHERE, MANUN HAYI EXISTING PU'),
  PollingModel(name: '004 JAMAâ€TMARE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '005 JAMAâ€TMARE, KOFAR WAZIRI EXISTING PU'),
  PollingModel(name: '006 TUMBURU YUGUDA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '007 KAI GAMARI, PRI. SCH. EXISTING PU'),
  PollingModel(name: '008 LAYARI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '009 KAFIN SULEI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '010 GAMADADI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '011 GWARAM, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '012 KAYA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '013 PANGURU, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '014 DONGOL CHADI, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '015 DONGOL ALEWA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '016 WADA JAURO GOJE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '017 JIMPITI GAJERE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '018 RAI ALHAJI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '019 MANARU, MANARU PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '020 GUDA LAMIDO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '021 KESU J./LAMIDO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '022 FARIN BANGO, FARIN BANGO PRI. SCH. EXISTING PU'),
  PollingModel(name: '023 KALTANGA FULANI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '024 KALTANGA BAKANO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '025 YALWA FADA, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '026 BADARI YIDI KAWU, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '027 TUNGO MANARU, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '028 ARDO SULEI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '029 BARRI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '030 WURO JAJI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '031 KUFA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '032 KESU ARDO, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '033 SAKARAMBU, PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '034 KESUFATTUDE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '035 YELWA, KOFAR SARKI EXISTING PU'),
  PollingModel(name: '036 T. WADA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '037 SAMBORI G. MADU, JAURO BABA SULE EXISTING PU'),
  PollingModel(name: '038 WUDIL, KOFAR J. WUDIL EXISTING PU'),
  PollingModel(name: '039 KADHERE GABAS II K. TAFIDA NEW PU'),
  PollingModel(name: '040 KADHERE GABAS III K. TAFIDA NEW PU'),
  PollingModel(name: '041 JAMAâ€TMARE K. JAURO TUMBURU J. PRI SCH NEW PU'),
  PollingModel(name: '042 JAMAâ€TMARE KOFAR WAZIRI II NEW PU'),
  PollingModel(name: '043 KALTANGA BAKANO II PUBLIC TRANSFORMER NEW PU'),
  PollingModel(name: '044 DONGOL CHADI II PRI. SCH. NEW PU'),
  PollingModel(name: '045 KANON KASHERE II , K. KASHERE PRI SCH. NEW PU'),
  PollingModel(name: '046 SAKARAMBU II PRI. SCH. NEW PU'),
  PollingModel(name: '001 KUMO S.YAKI, K. S. YAKI EXISTING PU'),
  PollingModel(name: '002 KUMO GALADIMA, LIB. VIEW CENTRE EXISTING PU'),
  PollingModel(name: '003 KUMO SARDAUNA, DOS OFFICE EXISTING PU'),
  PollingModel(name: '004 KUMO B-KASUWA, KOFAR S. YAKI EXISTING PU'),
  PollingModel(name: '005 KUMO S/YAKI, KUMO MARTENITY EXISTING PU'),
  PollingModel(name: '006 KUMO SARDAUNA, KUMO SARDAUNA EXISTING PU'),
  PollingModel(name: '007 KUMO FULOTI, KOFAR DANFULANI EXISTING PU'),
  PollingModel(name: '008 KUMO FULOTI, GOFAR DANKOMISHI EXISTING PU'),
  PollingModel(name: '009 KUMO BAKOSHI, CENTRAL PRI. SCH. EXISTING PU'),
  PollingModel(name: '010 KUMO FULOTI, KOFAR ADAMU EXISTING PU'),
  PollingModel(name: '011 KUMO FULOT, KOFAR LIMAN SHUIBU EXISTING PU'),
  PollingModel(name: '012 KUMO BAKOSHI, CENTRAL PRI. SCH. EXISTING PU'),
  PollingModel(name: '013 KUMO FULANI, JAURO TUKUR PRI. SCH. EXISTING PU'),
  PollingModel(name: '014 NAYINAWA, KOFAR J. DAUDA EXISTING PU'),
  PollingModel(name: '015 KUMO FULANI EAST, K. J. MAGAJI EXISTING PU'),
  PollingModel(name: '016 CHIROMA DAWA, K. CHIROMA DAWA EXISTING PU'),
  PollingModel(name: '017 GAUDARE, SHABBAL PRI. SCH. EXISTING PU'),
  PollingModel(name: '018 DAKKITI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '019 LAMBA J. MUSA, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '020 LERGO, LEGRO PRI. SCH. EXISTING PU'),
  PollingModel(name: '021 LAMBO J. A. BOSE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '022 KOMBANIYEL, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '023 NGAUDARE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '024 GARIN M. BA, GARIN M. BA PRI. SCH. EXISTING PU'),
  PollingModel(name: '025 WURO BAPPA, JAURO BAPPA EXISTING PU'),
  PollingModel(name: '026 KUMO GALADIMA II, LIB. VIEW CENTRE NEW PU'),
  PollingModel(name: '027 KUMO BAKOSHI II, CENTRAL PRI. SCH. NEW PU'),
  PollingModel(name: '029 KUMO BAKOSHI III, CENT PRI SCH NEW PU'),
  PollingModel(name: '030 KUMO SARKIN YAKI II, CENTRAL PRI. SCH. NEW PU'),
  PollingModel(
      name: '031 KUMO S. YAKI-KUMO MATERNITY II, CANTRAL PRI. SCH. NEW PU'),
  PollingModel(
      name: '032 KUMO FULOTI, KOFAR LIMAN SHUAIBU II KOFAR LIMAN NEW PU'),
  PollingModel(
      name: '033 KUMO FULOTI, KOFAR DANFULANI II, KOFAR DANFULANI NEW PU'),
  PollingModel(name: '034 KUMO FULOTI, KOFAR ADAMU II UNGUWAN TIKE NEW PU'),
  PollingModel(name: '035 KUMO FULANI II , JAURO TUKUR PRI. SCHOOL NEW PU'),
  PollingModel(name: '036 DAKKITI II, BAKIN RIJIYA OPEN SPACE NEW PU'),
  PollingModel(name: '037 GARIN LIMAN I, PRIMARY SCH. NEW PU'),
  PollingModel(name: '038 GARIN LIMAN II, PRIMARY SCH. NEW PU'),
  PollingModel(name: '001 BUBA WAZIRI, KOFAR MAI ANG. SEYOJI EXISTING PU'),
  PollingModel(name: '002 KUMO TERA, KOFAR JAURO UMMARU EXISTING PU'),
  PollingModel(name: '003 AKKOYEL I, AKKOYEL PRI. SCH. EXISTING PU'),
  PollingModel(name: '004 AKKOYEL II, AKKOYEL PRI. SCH. EXISTING PU'),
  PollingModel(name: '005 BANGU BANTASHI, KOFAR MANU BANGU EXISTING PU'),
  PollingModel(name: '006 GARKOYEL, KOFAR JAURO EXISTING PU'),
  PollingModel(
      name: '007 GARAZA, NOMADIC EDUCATION PRIMARY SCHOOL EXISTING PU'),
  PollingModel(name: '008 WURO GIYE, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '009 BUBA WAZIRI, KOFAR JAURO EXISTING PU'),
  PollingModel(name: '010 KUMO SHADORI, KOFAR MARAFA EXISTING PU'),
  ///////continue
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
  /////////
  PollingModel(name: '021 TSAMIYA, KOFAR J. TSAMIYA EXISTING PU'),
  PollingModel(name: '022 BUHARI ESTATE, BUHARI ESTATE EXISTING PU'),
  PollingModel(name: '023 IMMIGRATION OFFICE, IMMIGRATION OFFICE EXISTING PU'),
  PollingModel(
      name: '024 IMMIGRATION QUARTERS, IMMIGRATION QUARTERS EXISTING PU'),
  PollingModel(name: '025 WANZAM, K. ADAMU WANZAM EXISTING PU'),
  PollingModel(name: '026 UPPER BENUE, K. UPPER BENUE EXISTING PU'),
  PollingModel(name: '027 BAPPAH TIREBO, K/BAPPAH TIREBO EXISTING PU'),
  PollingModel(name: '028 MAI SAKA, KOFAR MAI SAKA EXISTING PU'),
  PollingModel(name: '029 J. I. ORJI, J. I. ORJI QUARTERS EXISTING PU'),
  PollingModel(name: '030 KOFAR UMARU YANKARI NEW PU'),
  PollingModel(name: '031 KOFAR SARKIN NOMA NEW PU'),
  PollingModel(name: '032 KOFAR USMAN FODIO NEW PU'),
  PollingModel(name: '033 K/MOHAMMED ALI KUMO NEW PU'),
  PollingModel(name: '034 KOFAR ALH. HARI NEW PU'),
  PollingModel(name: '035 KOFAR TUKUR MAI YADI NEW PU'),
  PollingModel(name: '036 KOFAR DADA BORNO NEW PU'),
  PollingModel(name: '037 KOFAN MALLAM HAMMA NEW PU'),
  PollingModel(name: '038 KOFAN BALA MAI KWALTA NEW PU'),
  PollingModel(name: '039 KOFAR MALLAM FARI NEW PU'),
  PollingModel(name: '040 KOFAR LAWAN BAWASA NEW PU'),
];
